apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  labels:
    app: nodejs-pipeline
    app.kubernetes.io/instance: nodejs-pipeline-instance
    app.kubernetes.io/name: nodejs-pipeline
  name: nodejs-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
     - name: source-repo
       type: string
     - name: image-repo
       type: string
  tasks:
    - name: clone-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.source-repo)"
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: build-image
      taskRef:
        kind: ClusterTask
        name: buildah
      runAfter:
        - clone-repository
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data

